var d=true,i=null,k=false;function l(){return function(){}}function n(a){return function(){return this[a]}}var aa=function(){var a=document.getElementsByTagName("script");var b=(a=a[a.length-1].getAttribute("src").match(/(^|(.*?\/))(OpenLayers\.js)(\?|$)/))?a[1]:"";return function(){return b}}(),o={};function ba(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")}
function ca(a){a=a.split("-");for(var b=a[0],c=1,e=a.length;c<e;c++){var f=a[c];b+=f.charAt(0).toUpperCase()+f.substring(1)}return b}function da(a,b,c){b||(b=window);return a.replace(ea,function(e,f){for(var g,h=f.split(/\.+/),j=0;j<h.length;j++){if(j==0)g=b;g=g[h[j]]}if(typeof g=="function")g=c?g.apply(i,c):g();return typeof g=="undefined"?"undefined":g})}var ea=/\$\{([\w.]+?)\}/g;
if(!String.prototype.Ie)String.prototype.Ie=function(a){p.warn(q("methodDeprecated",{newMethod:"OpenLayers.String.startsWith"}));return this.indexOf(a)==0};if(!String.prototype.contains)String.prototype.contains=function(a){p.warn(q("methodDeprecated",{newMethod:"OpenLayers.String.contains"}));return this.indexOf(a)!=-1};if(!String.prototype.Pe)String.prototype.Pe=function(){p.warn(q("methodDeprecated",{newMethod:"OpenLayers.String.trim"}));return ba(this)};
if(!String.prototype.Pd)String.prototype.Pd=function(){p.warn(q("methodDeprecated",{newMethod:"OpenLayers.String.camelize"}));return ca(this)};if(!Number.prototype.le)Number.prototype.le=function(a){p.warn(q("methodDeprecated",{newMethod:"OpenLayers.Number.limitSigDigs"}));var b=0;if(a>0)b=parseFloat(this.toPrecision(a));return b};function r(a,b){var c=Array.prototype.slice.apply(arguments,[2]);return function(){var e=c.concat(Array.prototype.slice.apply(arguments,[0]));return a.apply(b,e)}}
function fa(a,b){return function(c){return a.call(b,c||window.event)}}function ga(){return k}if(!Function.prototype.Md)Function.prototype.Md=function(){p.warn(q("methodDeprecated",{newMethod:"OpenLayers.Function.bind"}));Array.prototype.unshift.apply(arguments,[this]);return r.apply(i,arguments)};if(!Function.prototype.Nd)Function.prototype.Nd=function(a){p.warn(q("methodDeprecated",{newMethod:"OpenLayers.Function.bindAsEventListener"}));return fa(this,a)};
function ha(a,b,c){var e=[];if(Array.prototype.filter)e=a.filter(b,c);else{var f=a.length;if(typeof b!="function")throw new TypeError;for(var g=0;g<f;g++)if(g in a){var h=a[g];b.call(c,h,g,a)&&e.push(h)}}return e}function s(){var a=arguments.length,b=arguments[0],c=arguments[a-1],e=typeof c.s=="function"?c.s:function(){b.apply(this,arguments)};if(a>1){a=[e,b].concat(Array.prototype.slice.call(arguments).slice(1,a-1),c);ia.apply(i,a)}else e.prototype=c;return e}
function ia(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;var e,f,g;e=2;for(f=arguments.length;e<f;e++){g=arguments[e];if(typeof g==="function")g=g.prototype;u(a.prototype,g)}}function v(){for(var a=[],b=0,c=arguments.length;b<c;b++){var e=arguments[b];if(typeof e=="string")e=document.getElementById(e);if(arguments.length==1)return e;a.push(e)}return a}if(typeof window.ud==="undefined")window.ud=v;
function u(a,b){a=a||{};if(b){for(var c in b){var e=b[c];if(e!==undefined)a[c]=e}if(!(typeof window.Ia=="function"&&b instanceof window.Ia)&&b.hasOwnProperty&&b.hasOwnProperty("toString"))a.toString=b.toString}return a}function ja(a,b){for(var c=a.length-1;c>=0;c--)a[c]==b&&a.splice(c,1);return a}function w(a,b){if(typeof a.indexOf=="function")return a.indexOf(b);else{for(var c=0,e=a.length;c<e;c++)if(a[c]==b)return c;return-1}}
function y(a,b,c,e,f,g,h,j){if(b)a.id=b;if(c){a.style.left=c.x+"px";a.style.top=c.y+"px"}if(e){a.style.width=e.h+"px";a.style.height=e.g+"px"}if(f)a.style.position=f;if(g)a.style.border=g;if(h)a.style.overflow=h;if(parseFloat(j)>=0&&parseFloat(j)<1){a.style.filter="alpha(opacity="+j*100+")";a.style.opacity=j}else if(parseFloat(j)==1){a.style.filter="";a.style.opacity=""}}
function z(a,b,c,e,f,g,h,j){var m=document.createElement("div");if(e)m.style.backgroundImage="url("+e+")";a||(a=A("OpenLayersDiv"));f||(f="absolute");y(m,a,b,c,f,g,h,j);return m}function ka(a,b,c,e,f,g,h,j){var m=document.createElement("img");a||(a=A("OpenLayersDiv"));f||(f="relative");y(m,a,b,c,f,g,i,h);if(j){m.style.display="none";B.D(m,"load",r(la,m));B.D(m,"error",r(ma,m))}m.style.alt=a;m.Of="no";if(e)m.src=e;return m}
function la(){if(!this.va||this.map&&this.va==this.map.va)this.style.display="";C.dc(this,"olImageLoadError")}
function ma(){this.ib=this.ib?this.ib+1:1;if(this.ib<=0){var a=this.rd;if(a&&a instanceof Array&&a.length>1){var b=this.src.toString(),c,e;for(e=0;c=a[e];e++)if(b.indexOf(c)!=-1)break;var f=Math.floor(a.length*Math.random());f=a[f];for(e=0;f==c&&e++<4;){f=Math.floor(a.length*Math.random());f=a[f]}this.src=b.replace(c,f)}else this.src=this.src}else C.Na(this,"olImageLoadError");this.style.display=""}var na=i;
function oa(){if(na==i){var a=parseFloat(navigator.appVersion.split("MSIE")[1]),b=k;try{b=!!document.body.Kf}catch(c){}na=b&&a>=5.5&&a<7}return na}
function pa(a,b,c,e,f,g,h,j,m){y(a,b,c,e,g,i,i,m);b=a.childNodes[0];if(f)b.src=f;y(b,a.id+"_innerImage",i,e,"relative",h);if(oa()){if(a.style.display!="none")a.style.display="inline-block";if(j==i)j="scale";a.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+b.src+"', sizingMethod='"+j+"')";if(parseFloat(a.style.opacity)>=0&&parseFloat(a.style.opacity)<1)a.style.filter+=" alpha(opacity="+a.style.opacity*100+")";b.style.filter="alpha(opacity=0)"}}
function qa(a,b,c,e,f,g,h,j,m){var x=z(),t=ka(i,i,i,i,i,i,i,k);x.appendChild(t);if(m){t.style.display="none";B.D(t,"load",r(la,x));B.D(t,"error",r(ma,x))}pa(x,a,b,c,e,f,g,h,j);return x}function E(a,b){a=a||{};var c=typeof window.Ia=="function"&&b instanceof window.Ia,e;for(e in b)if(a[e]===undefined||!c&&b.hasOwnProperty&&b.hasOwnProperty(e)&&!a.hasOwnProperty(e))a[e]=b[e];if(!c&&b&&b.hasOwnProperty&&b.hasOwnProperty("toString")&&!a.hasOwnProperty("toString"))a.toString=b.toString;return a}
function ra(a){var b=[],c;for(c in a){var e=a[c];if(e!=i&&typeof e!="function"){if(typeof e=="object"&&e.constructor==Array){for(var f=[],g,h=0,j=e.length;h<j;h++){g=e[h];f.push(encodeURIComponent(g===i||g===undefined?"":g))}e=f.join(",")}else e=encodeURIComponent(e);b.push(encodeURIComponent(c)+"="+e)}}return b.join("&")}function F(a,b){if(b==i)b=14;return a=b==0?parseFloat(a):parseFloat(parseFloat(a).toPrecision(b))}var G=1/298.257223563;
function sa(a,b){var c=(b.d-a.d)*Math.PI/180,e=Math.atan((1-G)*Math.tan(a.f*Math.PI/180)),f=Math.atan((1-G)*Math.tan(b.f*Math.PI/180)),g=Math.sin(e);e=Math.cos(e);var h=Math.sin(f);f=Math.cos(f);for(var j=c,m=2*Math.PI,x=20;Math.abs(j-m)>1.0E-12&&--x>0;){var t=Math.sin(j),D=Math.cos(j),J=Math.sqrt(f*t*f*t+(e*h-g*f*D)*(e*h-g*f*D));if(J==0)return 0;D=g*h+e*f*D;var Z=Math.atan2(J,D),K=Math.asin(e*f*t/J),M=Math.cos(K)*Math.cos(K);t=D-2*g*h/M;var S=G/16*M*(4+G*(4-3*M));m=j;j=c+(1-S)*G*Math.sin(K)*(Z+S*
J*(t+S*D*(-1+2*t*t)))}if(x==0)return NaN;c=M*2.723316066819453E11/4.0408299984087055E13;g=c/1024*(256+c*(-128+c*(74-47*c)));return(6356752.3142*(1+c/16384*(4096+c*(-768+c*(320-175*c))))*(Z-g*J*(t+g/4*(D*(-1+2*t*t)-g/6*t*(-3+4*J*J)*(-3+4*t*t))))).toFixed(3)/1E3}
function ta(a){a=a||window.location.href;var b="";if(a.indexOf("?")!=-1)b=a.substring(a.indexOf("?")+1,a.indexOf("#")!=-1?a.indexOf("#"):a.length);a={};b=b.split(/[&;]/);for(var c=0,e=b.length;c<e;++c){var f=b[c].split("=");if(f[0]){var g=f[0];try{g=decodeURIComponent(g)}catch(h){g=unescape(g)}f=(f[1]||"").replace(/\+/g," ");try{f=decodeURIComponent(f)}catch(j){f=unescape(f)}f=f.split(",");if(f.length==1)f=f[0];a[g]=f}}return a}var ua=0;function A(a){if(a==i)a="id_";ua+=1;return a+ua}
var H={inches:1,ft:12,mi:63360,m:39.3701,km:39370.1,dd:4374754,yd:36};H["in"]=H.he;H.degrees=H.Ef;H.nmi=1852*H.mg;
u(H,{Inch:H.he,Meter:39.37,Foot:12,IFoot:11.999976,ClarkeFoot:11.999868327581488,SearsFoot:11.999955194477684,GoldCoastFoot:11.999964589846002,IInch:0.9999979999999999,MicroInch:9.99998E-4,Mil:9.99998E-7,Centimeter:0.3937,Kilometer:39370,Yard:36,SearsYard:35.99986558343306,IndianYard:35.99987015540864,IndianYd37:35.999740205100004,IndianYd62:35.999880755999996,IndianYd75:35.999868945,IndianFoot:11.9999567087,IndianFt37:11.9999134017,IndianFt62:11.999960252000001,IndianFt75:11.999956315,Mile:63360,
IYard:35.999928,IMile:63359.87328,NautM:72913.24,"Lat-66":4367838.370169282,"Lat-83":4367954.152606599,Decimeter:3.9370000000000003,Millimeter:0.03937,Dekameter:393.7,Decameter:393.7,Hectometer:3937,GermanMeter:39.370535294205006,CaGrid:39.359685060000004,ClarkeChain:791.991309620512,GunterChain:792.0000000000001,BenoitChain:791.9977268035781,SearsChain:791.9970428354235,ClarkeLink:7.91991309620512,GunterLink:7.920000000000001,BenoitLink:7.919977268035781,SearsLink:7.919970428354236,Rod:198.00000000000014,
IntnlChain:791.998416,IntnlLink:7.91998416,Perch:198.00000000000014,Pole:198.00000000000014,Furlong:7919.999999999997,Rood:148.75036777426,CapeFoot:11.999868185255002,Brealey:14763.75,ModAmFt:12.000458400000001,Fathom:71.999856,"NautM-UK":72959.85408,"50kilometers":1968500,"150kilometers":5905500});
u(H,{mm:H.Meter/1E3,cm:H.Meter/100,dm:H.Meter*100,km:H.Meter*1E3,kmi:H.nmi,fath:H.Fathom,ch:H.IntnlChain,link:H.IntnlLink,"us-in":H.inches,"us-ft":H.Foot,"us-yd":H.Yard,"us-ch":H.GunterChain,"us-mi":H.Mile,"ind-yd":H.IndianYd37,"ind-ft":H.IndianFt37,"ind-ch":791.9942845122});function I(a,b){var c;if(a){if(b==i)b="degrees";c=1/((a>1?1/a:a)*H[b]*72)}return c}function L(a,b){if(b==i)b="degrees";return a*H[b]*72}
function va(a,b,c){c=c||{};E(c,{ignoreCase:d,ge:d,fe:d});a=wa(a,c);b=wa(b,c);for(var e in a)if(e!=="args")if(a[e]!=b[e])return k;for(e in a.Oa){if(a.Oa[e]!=b.Oa[e])return k;delete b.Oa[e]}for(e in b.Oa)return k;return d}
function wa(a,b){b=b||{};if(!/^\w+:\/\//.test(a)){var c=window.location,e=c.port?":"+c.port:"";e=c.protocol+"//"+c.host.split(":").shift()+e;if(a.indexOf("/")===0)a=e+a;else{c=c.pathname.split("/");c.pop();a=e+c.join("/")+"/"+a}}if(b.ignoreCase)a=a.toLowerCase();c=document.createElement("a");c.href=a;e={};e.host=c.host.split(":").shift();e.protocol=c.protocol;e.port=b.ge?c.port=="80"||c.port=="0"?"":c.port:c.port==""||c.port=="0"?"80":c.port;e.hash=b.fe||c.hash==="#"?"":c.hash;var f=c.search;if(!f){f=
a.indexOf("?");f=f!=-1?a.substr(f):""}e.Oa=ta(f);e.pathname=c.pathname.charAt(0)=="/"?c.pathname:"/"+c.pathname;return e}function xa(){var a="",b=navigator.userAgent.toLowerCase();if(b.indexOf("opera")!=-1)a="opera";else if(b.indexOf("msie")!=-1)a="msie";else if(b.indexOf("safari")!=-1)a="safari";else if(b.indexOf("mozilla")!=-1)a=b.indexOf("firefox")!=-1?"firefox":"mozilla";return a}
for(var C={Ue:function(a){return v(a).style.display!="none"},Lg:function(){for(var a=0,b=arguments.length;a<b;a++){var c=v(arguments[a]),e=C.Ue(c)?"hide":"show";C[e](c)}},ra:function(){for(var a=0,b=arguments.length;a<b;a++){var c=v(arguments[a]);if(c)c.style.display="none"}},show:function(){for(var a=0,b=arguments.length;a<b;a++){var c=v(arguments[a]);if(c)c.style.display=""}},remove:function(a){a=v(a);a.parentNode.removeChild(a)},da:function(a){a=v(a);return a.offsetHeight},Sf:function(a){a=v(a);
if(C.Xb(a,"display")!="none")return{width:a.offsetWidth,height:a.offsetHeight};var b=a.style,c=b.visibility,e=b.position,f=b.display;b.visibility="hidden";b.position="absolute";b.display="";var g=a.clientWidth;a=a.clientHeight;b.display=f;b.position=e;b.visibility=c;return{width:g,height:a}},Rc:function(a,b){var c=a.className;return!!c&&RegExp("(^|\\s)"+b+"(\\s|$)").test(c)},Na:function(a,b){C.Rc(a,b)||(a.className+=(a.className?" ":"")+b);return a},dc:function(a,b){var c=a.className;if(c)a.className=
ba(c.replace(RegExp("(^|\\s+)"+b+"(\\s+|$)")," "));return a},Mg:function(a,b){C.Rc(a,b)?C.dc(a,b):C.Na(a,b);return a},Xb:function(a,b){a=v(a);var c=i;if(a&&a.style){c=a.style[ca(b)];if(!c)if(document.defaultView&&document.defaultView.getComputedStyle)c=(c=document.defaultView.getComputedStyle(a,i))?c.getPropertyValue(b):i;else if(a.currentStyle)c=a.currentStyle[ca(b)];var e=["left","top","right","bottom"];if(window.opera&&w(e,b)!=-1&&C.Xb(a,"position")=="static")c="auto"}return c=="auto"?i:c}},N=
s({h:0,g:0,s:function(a,b){this.h=parseFloat(a);this.g=parseFloat(b)},toString:function(){return"w="+this.h+",h="+this.g},j:function(){return new N(this.h,this.g)},ba:function(a){var b=k;if(a!=i)b=this.h==a.h&&this.g==a.g||isNaN(this.h)&&isNaN(this.g)&&isNaN(a.h)&&isNaN(a.g);return b},r:"OpenLayers.Size"}),p={log:l(),Ff:l(),info:l(),warn:l(),error:l(),Pg:function(a){alert(a)},zf:l(),dir:l(),Hf:l(),Ng:l(),hg:l(),ig:l(),cb:l(),Gg:l(),profile:l(),tg:l(),Df:l(),r:"OpenLayers.Console"},ya=document.getElementsByTagName("script"),
za=0,Aa=ya.length;za<Aa;++za)if(ya[za].src.indexOf("firebug.js")!=-1)if(console){u(p,console);break}
var O=s({left:i,bottom:i,right:i,top:i,Qa:i,s:function(a,b,c,e){if(a!=i)this.left=F(a);if(b!=i)this.bottom=F(b);if(c!=i)this.right=F(c);if(e!=i)this.top=F(e)},j:function(){return new O(this.left,this.bottom,this.right,this.top)},ba:function(a){var b=k;if(a!=i)b=this.left==a.left&&this.right==a.right&&this.top==a.top&&this.bottom==a.bottom;return b},toString:function(){return"left-bottom=("+this.left+","+this.bottom+") right-top=("+this.right+","+this.top+")"},Hg:function(a){return a===d?[this.bottom,
this.left,this.top,this.right]:[this.left,this.bottom,this.right,this.top]},Ig:function(a,b){if(a==i)a=6;var c=Math.pow(10,a),e=Math.round(this.left*c)/c,f=Math.round(this.bottom*c)/c,g=Math.round(this.right*c)/c;c=Math.round(this.top*c)/c;return b===d?f+","+e+","+c+","+g:e+","+f+","+g+","+c},Jg:function(){return new o.Ja.rf([new o.Ja.nf([new o.Ja.Jb(this.left,this.bottom),new o.Ja.Jb(this.right,this.bottom),new o.Ja.Jb(this.right,this.top),new o.Ja.Jb(this.left,this.top)])])},M:function(){return this.right-
this.left},da:function(){return this.top-this.bottom},Q:function(){return new N(this.M(),this.da())},Pf:function(){return new P((this.left+this.right)/2,(this.bottom+this.top)/2)},pa:function(){if(!this.Qa)this.Qa=new R((this.left+this.right)/2,(this.bottom+this.top)/2);return this.Qa},scale:function(a,b){if(b==i)b=this.pa();var c,e;if(b.r=="OpenLayers.LonLat"){c=b.d;e=b.f}else{c=b.x;e=b.y}return new O((this.left-c)*a+c,(this.bottom-e)*a+e,(this.right-c)*a+c,(this.top-e)*a+e)},add:function(a,b){if(a==
i||b==i){var c=q("boundsAddError");p.error(c);return i}return new O(this.left+a,this.bottom+b,this.right+a,this.top+b)},extend:function(a){var b=i;if(a){switch(a.r){case "OpenLayers.LonLat":b=new O(a.d,a.f,a.d,a.f);break;case "OpenLayers.Geometry.Point":b=new O(a.x,a.y,a.x,a.y);break;case "OpenLayers.Bounds":b=a}if(b){this.Qa=i;if(this.left==i||b.left<this.left)this.left=b.left;if(this.bottom==i||b.bottom<this.bottom)this.bottom=b.bottom;if(this.right==i||b.right>this.right)this.right=b.right;if(this.top==
i||b.top>this.top)this.top=b.top}}},Cc:function(a,b){return this.contains(a.d,a.f,b)},Cf:function(a,b){return this.contains(a.x,a.y,b)},contains:function(a,b,c){if(c==i)c=d;if(a==i||b==i)return k;a=F(a);b=F(b);var e=k;return e=c?a>=this.left&&a<=this.right&&b>=this.bottom&&b<=this.top:a>this.left&&a<this.right&&b>this.bottom&&b<this.top},Vc:function(a,b){if(b==i)b=d;var c=k,e=this.left==a.right||this.right==a.left||this.top==a.bottom||this.bottom==a.top;if(b||!e){c=a.top>=this.bottom&&a.top<=this.top||
this.top>a.bottom&&this.top<a.top;e=a.left>=this.left&&a.left<=this.right||this.left>=a.left&&this.left<=a.right;var f=a.right>=this.left&&a.right<=this.right||this.right>=a.left&&this.right<=a.right;c=(a.bottom>=this.bottom&&a.bottom<=this.top||this.bottom>=a.bottom&&this.bottom<=a.top||c)&&(e||f)}return c},Rb:function(a,b,c){if(b==i)b=k;if(c==i)c=d;var e=this.contains(a.left,a.bottom,c),f=this.contains(a.right,a.bottom,c),g=this.contains(a.left,a.top,c);a=this.contains(a.right,a.top,c);return b?
e||f||g||a:e&&f&&g&&a},Gf:function(a){var b="",c=this.pa();b+=a.f<c.f?"b":"t";b+=a.d<c.d?"l":"r";return b},transform:function(a,b){this.Qa=i;var c=T.transform({x:this.left,y:this.bottom},a,b),e=T.transform({x:this.right,y:this.bottom},a,b),f=T.transform({x:this.left,y:this.top},a,b),g=T.transform({x:this.right,y:this.top},a,b);this.left=Math.min(c.x,f.x);this.bottom=Math.min(c.y,e.y);this.right=Math.max(e.x,g.x);this.top=Math.max(f.y,g.y);return this},$:function(a,b){b=b||{};var c=b.lg||0,e=b.yg||
0,f=this.j();if(a){for(;f.left<a.left&&f.right-e<=a.left;)f=f.add(a.M(),0);for(;f.left+c>=a.right&&f.right>a.right;)f=f.add(-a.M(),0)}return f},r:"OpenLayers.Bounds"});O.Ud=function(a){return O.Td(a.split(","))};O.Td=function(a){return new O(parseFloat(a[0]),parseFloat(a[1]),parseFloat(a[2]),parseFloat(a[3]))};O.Nf=function(a){return new O(0,a.g,a.h,0)};O.sg=function(a){var b="";b+=a.charAt(0)=="t"?"b":"t";b+=a.charAt(1)=="l"?"r":"l";return b};
var R=s({d:0,f:0,s:function(a,b){this.d=F(a);this.f=F(b)},toString:function(){return"lon="+this.d+",lat="+this.f},Kg:function(){return this.d+", "+this.f},j:function(){return new R(this.d,this.f)},add:function(a,b){if(a==i||b==i){var c=q("lonlatAddError");p.error(c);return i}return new R(this.d+F(a),this.f+F(b))},ba:function(a){var b=k;if(a!=i)b=this.d==a.d&&this.f==a.f||isNaN(this.d)&&isNaN(this.f)&&isNaN(a.d)&&isNaN(a.f);return b},transform:function(a,b){var c=T.transform({x:this.d,y:this.f},a,
b);this.d=c.x;this.f=c.y;return this},$:function(a){var b=this.j();if(a){for(;b.d<a.left;)b.d+=a.M();for(;b.d>a.right;)b.d-=a.M()}return b},r:"OpenLayers.LonLat"});R.Ud=function(a){a=a.split(",");return new R(a[0],a[1])};
var P=s({x:0,y:0,s:function(a,b){this.x=parseFloat(a);this.y=parseFloat(b)},toString:function(){return"x="+this.x+",y="+this.y},j:function(){return new P(this.x,this.y)},ba:function(a){var b=k;if(a!=i)b=this.x==a.x&&this.y==a.y||isNaN(this.x)&&isNaN(this.y)&&isNaN(a.x)&&isNaN(a.y);return b},add:function(a,b){if(a==i||b==i){var c=q("pixelAddError");p.error(c);return i}return new P(this.x+a,this.y+b)},qg:function(a){var b=this.j();if(a)b=this.add(a.x,a.y);return b},r:"OpenLayers.Pixel"}),U=s({id:i,
map:i,b:i,type:i,Kd:k,wa:"",title:"",Pa:k,aa:i,Y:i,A:i,a:i,ja:["activate","deactivate"],s:function(a){this.wa=this.r.replace("OpenLayers.","ol").replace(/\./g,"");u(this,a);this.a=new Ba(this,i,this.ja);this.A instanceof Object&&this.a.yb(this.A);if(this.id==i)this.id=A(this.r+"_")},t:function(){if(this.a){this.A&&this.a.db(this.A);this.a.t();this.a=i}this.A=i;if(this.Y){this.Y.t();this.Y=i}if(this.Ua){for(var a in this.Ua)this.Ua.hasOwnProperty(a)&&typeof this.Ua[a].t=="function"&&this.Ua[a].t();
this.Ua=i}if(this.map){this.map.we(this);this.map=i}},Eb:function(a){this.map=a;this.Y&&this.Y.Eb(a)},P:function(a){if(this.b==i){this.b=z(this.id);this.b.className=this.wa;if(!this.Kd){this.b.className+=" olControlNoSelect";this.b.setAttribute("unselectable","on",0);this.b.rg=ga}if(this.title!="")this.b.title=this.title}if(a!=i)this.position=a.j();this.moveTo(this.position);return this.b},moveTo:function(a){if(a!=i&&this.b!=i){this.b.style.left=a.x+"px";this.b.style.top=a.y+"px"}},la:function(){if(this.aa)return k;
this.Y&&this.Y.la();this.aa=d;this.map&&C.Na(this.map.v,this.wa.replace(/ /g,"")+"Active");this.a.o("activate");return d},oa:function(){if(this.aa){this.Y&&this.Y.oa();this.aa=k;this.map&&C.dc(this.map.v,this.wa.replace(/ /g,"")+"Active");this.a.o("deactivate");return d}return k},r:"OpenLayers.Control"});U.Ma=1;U.Ad=2;U.Bd=3;
var V={code:i,Rd:"en",L:function(){V.code||V.De();return V.code},De:function(a){var b;a||(a=xa()=="msie"?navigator.Qg:navigator.language);a=a.split("-");a[0]=a[0].toLowerCase();if(typeof V[a[0]]=="object")b=a[0];if(a[1]){var c=a[0]+"-"+a[1].toUpperCase();if(typeof V[c]=="object")b=c}if(!b){p.warn("Failed to find OpenLayers.Lang."+a.join("-")+" dictionary, falling back to default language");b=V.Rd}V.code=b},translate:function(a,b){var c=V[V.L()][a];c||(c=a);if(b)c=da(c,b);return c}},q=V.translate,
Da=s({vd:10,Hc:i,lb:i,Tb:i,duration:i,K:i,cb:i,Aa:i,bc:k,s:function(a){this.Hc=a?a:Ca},start:function(a,b,c,e){this.bc=d;this.lb=a;this.Tb=b;this.duration=c;this.K=e.K;this.cb=0;if(this.Aa){window.clearInterval(this.Aa);this.Aa=i}this.K&&this.K.start&&this.K.start.call(this,this.lb);this.Aa=window.setInterval(r(this.play,this),this.vd)},stop:function(){if(this.bc){this.K&&this.K.Fc&&this.K.Fc.call(this,this.Tb);window.clearInterval(this.Aa);this.Aa=i;this.bc=k}},play:function(){var a={},b;for(b in this.lb){var c=
this.lb[b],e=this.Tb[b];if(c==i||e==i||isNaN(c)||isNaN(e))p.error("invalid value for Tween");a[b]=this.Hc.apply(this,[this.cb,c,e-c,this.duration])}this.cb++;this.K&&this.K.Gc&&this.K.Gc.call(this,a);this.cb>this.duration&&this.stop()},r:"OpenLayers.Tween"});function Ca(a,b,c,e){return a==e?b+c:c*(-Math.pow(2,-10*a/e)+1)+b}
U.Pan=s(U,{J:50,direction:i,type:U.Ma,F:i,s:function(a,b){this.direction=a;this.r+=this.direction;this.F={};U.prototype.s.apply(this,[b])},Hb:function(){switch(this.direction){case U.Pan.nc:this.map.Ab(0,-this.J,this.F);break;case U.Pan.oc:this.map.Ab(0,this.J,this.F);break;case U.Pan.rc:this.map.Ab(-this.J,0,this.F);break;case U.Pan.mc:this.map.Ab(this.J,0,this.F)}},r:"OpenLayers.Control.Pan"});U.Pan.nc="North";U.Pan.oc="South";U.Pan.mc="East";U.Pan.rc="West";
U.gb=s(U,{controls:i,Pa:d,Dc:i,ld:k,kb:i,s:function(a){U.prototype.s.apply(this,[a]);this.controls=[];this.kb={}},t:function(){U.prototype.t.apply(this,arguments);for(var a=this.controls.length-1;a>=0;a--){this.controls[a].a&&this.controls[a].a.db({activate:this.I,deactivate:this.I,scope:this});B.ab(this.controls[a].ta);this.controls[a].ta=i}this.kb=i},la:function(){if(U.prototype.la.apply(this,arguments)){for(var a,b=0,c=this.controls.length;b<c;b++){a=this.controls[b];if(a===this.Dc||this.ld&&this.kb[a.id])a.la()}if(this.ld===
d)this.Dc=i;this.I();return d}else return k},oa:function(){if(U.prototype.oa.apply(this,arguments)){for(var a,b=0,c=this.controls.length;b<c;b++){a=this.controls[b];this.kb[a.id]=a.oa()}this.I();return d}else return k},P:function(){U.prototype.P.apply(this,arguments);this.uc(this.controls);return this.b},I:function(){for(var a=this.b.childNodes.length-1;a>=0;a--)this.b.removeChild(this.b.childNodes[a]);this.b.innerHTML="";if(this.aa){a=0;for(var b=this.controls.length;a<b;a++){var c=this.controls[a].ta;
c.className=this.controls[a].aa?this.controls[a].wa+"ItemActive":this.controls[a].wa+"ItemInactive";this.b.appendChild(c)}}},Hd:function(a){if(!this.aa)return k;if(a.type==U.Ma){a.Hb();this.I()}else if(a.type==U.Ad)a.aa?a.oa():a.la();else{for(var b,c=0,e=this.controls.length;c<e;c++){b=this.controls[c];if(b!=a&&(b.type===U.Bd||b.type==i))b.oa()}a.la()}},Lb:function(a){a instanceof Array||(a=[a]);this.controls=this.controls.concat(a);for(var b=0,c=a.length;b<c;b++){a[b].ta=document.createElement("div");
if(a[b].title!="")a[b].ta.title=a[b].title;B.D(a[b].ta,"click",r(this.qe,this,a[b]));B.D(a[b].ta,"dblclick",r(this.re,this,a[b]));B.D(a[b].ta,"mousedown",fa(B.stop))}if(this.map){this.uc(a);this.I()}},uc:function(a){for(var b,c=0,e=a.length;c<e;c++){b=a[c];if(b.Pa===d){b.Pa=k;this.map.Kb(b);b.Pa=d}else{this.map.Kb(b);b.oa()}b.a.yb({activate:this.I,deactivate:this.I,scope:this})}},qe:function(a,b){B.stop(b?b:window.event);this.Hd(a)},re:function(a,b){B.stop(b?b:window.event)},qb:function(a,b){var c=
typeof b.test=="function";return ha(this.controls,function(e){return e[a]==b||c&&b.test(e[a])})},Qf:function(a){return this.qb("name",a)},Xd:function(a){return this.qb("CLASS_NAME",a)},r:"OpenLayers.Control.Panel"});U.Dd=s(U,{type:U.Ma,Hb:function(){this.map.Ve()},r:"OpenLayers.Control.ZoomIn"});U.Ed=s(U,{type:U.Ma,Hb:function(){this.map.We()},r:"OpenLayers.Control.ZoomOut"});U.Gd=s(U,{type:U.Ma,Hb:function(){this.map&&this.map.Xe()},r:"OpenLayers.Control.ZoomToMaxExtent"});
var B={O:k,df:8,lf:9,jf:13,gf:27,hf:37,mf:38,kf:39,ff:40,ef:46,element:function(a){return a.target||a.srcElement},jg:function(a){return a.which&&a.which==1||a.button&&a.button==1},kg:function(a){return a.which&&a.which==3||a.button&&a.button==2},stop:function(a,b){if(!b)if(a.preventDefault)a.preventDefault();else a.returnValue=k;if(a.stopPropagation)a.stopPropagation();else a.cancelBubble=d},Lf:function(a,b){for(var c=B.element(a);c.parentNode&&(!c.tagName||c.tagName.toUpperCase()!=b.toUpperCase());)c=
c.parentNode;return c},D:function(a,b,c,e){a=v(a);e=e||k;if(b=="keypress"&&(navigator.appVersion.match(/Konqueror|Safari|KHTML/)||a.attachEvent))b="keydown";if(!this.O)this.O={};if(!a.jb){var f="eventCacheID_";if(a.id)f=a.id+"_"+f;a.jb=A(f)}f=a.jb;this.O[f]||(this.O[f]=[]);this.O[f].push({element:a,name:b,observer:c,useCapture:e});if(a.addEventListener)a.addEventListener(b,c,e);else a.attachEvent&&a.attachEvent("on"+b,c)},ab:function(a){a=v(a).jb;this.sc(B.O[a])},sc:function(a){if(a)for(var b=a.length-
1;b>=0;b--){var c=a[b];B.Gb.apply(this,[c.element,c.name,c.pe,c.Te])}},Gb:function(a,b,c,e){e=e||k;a=v(a);var f=a.jb;if(b=="keypress")if(navigator.appVersion.match(/Konqueror|Safari|KHTML/)||a.detachEvent)b="keydown";var g=k,h=B.O[f];if(h)for(var j=0;!g&&j<h.length;){var m=h[j];if(m.name==b&&m.pe==c&&m.Te==e){h.splice(j,1);h.length==0&&delete B.O[f];g=d;break}j++}if(g)if(a.removeEventListener)a.removeEventListener(b,c,e);else a&&a.detachEvent&&a.detachEvent("on"+b,c);return g},Re:function(){if(B&&
B.O){for(var a in B.O)B.sc.apply(this,[B.O[a]]);B.O=k}},r:"OpenLayers.Event"};B.D(window,"unload",B.Re,k);if(window.Ia)E(window.Ia,B);else Event=B;
var Ba=s({lc:["mouseover","mouseout","mousedown","mouseup","mousemove","click","dblclick","rightclick","dblrightclick","resize","focus","blur"],T:i,object:i,element:i,ob:i,Sb:i,Ra:i,Zb:k,Qb:i,s:function(a,b,c,e,f){u(this,f);this.object=a;this.Ra=e;this.T={};this.Sb=fa(this.ee,this);this.Qb=r(this.Pb,this);this.ob=[];if(c!=i){a=0;for(e=c.length;a<e;a++)this.Mb(c[a])}b!=i&&this.yc(b)},t:function(){if(this.element){B.ab(this.element);this.element.Sc&&B.Gb(window,"scroll",this.Qb)}this.Sb=this.Ra=this.ob=
this.object=this.T=this.element=i},Mb:function(a){if(!this.T[a]){this.ob.push(a);this.T[a]=[]}},yc:function(a){this.element&&B.ab(this.element);this.element=a;for(var b=0,c=this.lc.length;b<c;b++){var e=this.lc[b];this.Mb(e);B.D(a,e,this.Sb)}B.D(a,"dragstart",B.stop)},yb:function(a){for(var b in a)b!="scope"&&this.Z(b,a.scope,a[b])},Z:function(a,b,c){if(c!=i&&w(this.ob,a)!=-1){if(b==i)b=this.object;this.T[a].push({ac:b,Vb:c})}},vg:function(a,b,c){if(c!=i){if(b==i)b=this.object;a=this.T[a];a!=i&&a.unshift({ac:b,
Vb:c})}},db:function(a){for(var b in a)b!="scope"&&this.kc(b,a.scope,a[b])},kc:function(a,b,c){if(b==i)b=this.object;a=this.T[a];if(a!=i)for(var e=0,f=a.length;e<f;e++)if(a[e].ac==b&&a[e].Vb==c){a.splice(e,1);break}},remove:function(a){if(this.T[a]!=i)this.T[a]=[]},o:function(a,b){var c=this.T[a];if(!(!c||c.length==0)){if(b==i)b={};b.object=this.object;b.element=this.element;if(!b.type)b.type=a;c=c.slice();for(var e,f=0,g=c.length;f<g;f++){e=c[f];e=e.Vb.apply(e.ac,[b]);if(e!=undefined&&e==k)break}this.Ra||
B.stop(b,d);return e}},ee:function(a){if(this.Zb)a.Rg=this.ae(a);this.o(a.type,a)},Pb:function(){this.element.Fa=i;this.element.wb=i;this.element.Ea=i},ae:function(a){if(this.Zb){if(!this.element.Sc){B.D(window,"scroll",this.Qb);this.element.Sc=d}}else this.Pb();if(!this.element.Fa)this.element.Fa=[document.documentElement.scrollLeft||document.body.scrollLeft,document.documentElement.scrollTop||document.body.scrollTop];if(!this.element.wb)this.element.wb=[document.documentElement.clientLeft||0,document.documentElement.clientTop||
0];if(!this.element.Ea){for(var b=this.element,c=this.element,e=0,f=0,g=c,h=c;g;){if(g==document.body)if(C.Xb(h,"position")=="absolute")break;e+=g.offsetTop||0;f+=g.offsetLeft||0;h=g;try{g=g.offsetParent}catch(j){p.error(q("pagePositionFailed",{elemId:g.id}));break}}for(g=c;g;){e-=g.scrollTop||0;f-=g.scrollLeft||0;g=g.parentNode}b.Ea=[f,e];this.element.Ea[0]+=this.element.Fa[0];this.element.Ea[1]+=this.element.Fa[1]}return new P(a.clientX+this.element.Fa[0]-this.element.Ea[0]-this.element.wb[0],a.clientY+
this.element.Fa[1]-this.element.Ea[1]-this.element.wb[1])},r:"OpenLayers.Events"});
V.Jf={unhandledRequest:"Unhandled request return ${statusText}",permalink:"Permalink",overlays:"Overlays",baseLayer:"Base Layer",sameProjection:"The overview map only works when it is in the same projection as the main map",readNotImplemented:"Read not implemented.",writeNotImplemented:"Write not implemented.",noFID:"Can't update a feature for which there is no FID.",errorLoadingGML:"Error in loading GML file ${url}",browserNotSupported:"Your browser does not support vector rendering. Currently supported renderers are:\n${renderers}",
componentShouldBe:"addFeatures : component should be an ${geomType}",getFeatureError:"getFeatureFromEvent called on layer with no renderer. This usually means you destroyed a layer, but not some handler which is associated with it.",minZoomLevelError:"The minZoomLevel property is only intended for use with the FixedZoomLevels-descendent layers. That this wfs layer checks for minZoomLevel is a relic of thepast. We cannot, however, remove it without possibly breaking OL based applications that may depend on it. Therefore we are deprecating it -- the minZoomLevel check below will be removed at 3.0. Please instead use min/max resolution setting as described here: http://trac.openlayers.org/wiki/SettingZoomLevels",
commitSuccess:"WFS Transaction: SUCCESS ${response}",commitFailed:"WFS Transaction: FAILED ${response}",googleWarning:"The Google Layer was unable to load correctly.<br><br>To get rid of this message, select a new BaseLayer in the layer switcher in the upper-right corner.<br><br>Most likely, this is because the Google Maps library script was either not included, or does not contain the correct API key for your site.<br><br>Developers: For help getting this working correctly, <a href='http://trac.openlayers.org/wiki/Google' target='_blank'>click here</a>",
getLayerWarning:"The ${layerType} Layer was unable to load correctly.<br><br>To get rid of this message, select a new BaseLayer in the layer switcher in the upper-right corner.<br><br>Most likely, this is because the ${layerLib} library script was not correctly included.<br><br>Developers: For help getting this working correctly, <a href='http://trac.openlayers.org/wiki/${layerLib}' target='_blank'>click here</a>",scale:"Scale = 1 : ${scaleDenom}",W:"W",E:"E",N:"N",S:"S",graticule:"Graticule",layerAlreadyAdded:"You tried to add the layer: ${layerName} to the map, but it has already been added",
reprojectDeprecated:"You are using the 'reproject' option on the ${layerName} layer. This option is deprecated: its use was designed to support displaying data over commercial basemaps, but that functionality should now be achieved by using Spherical Mercator support. More information is available from http://trac.openlayers.org/wiki/SphericalMercator.",methodDeprecated:"This method has been deprecated and will be removed in 3.0. Please use ${newMethod} instead.",boundsAddError:"You must pass both x and y values to the add function.",
lonlatAddError:"You must pass both lon and lat values to the add function.",pixelAddError:"You must pass both x and y values to the add function.",unsupportedGeometryType:"Unsupported geometry type: ${geomType}",pagePositionFailed:"OpenLayers.Util.pagePosition failed: element with id ${elemId} may be misplaced.",filterEvaluateNotImplemented:"evaluate is not implemented for this filter type.",end:""};
var T=s({U:i,cc:i,s:function(a,b){u(this,b);this.cc=a;if(window.uf)this.U=new Proj4js.tf(a)},L:function(){return this.U?this.U.Eg:this.cc},sb:function(){return this.U?this.U.z:i},toString:function(){return this.L()},ba:function(a){return a&&a.L?this.L()==a.L():k},t:function(){delete this.U;delete this.cc},r:"OpenLayers.Projection"});T.Ga={};T.wf=function(a,b,c){T.Ga[a]||(T.Ga[a]={});T.Ga[a][b]=c};
T.transform=function(a,b,c){if(b.U&&c.U)a=Proj4js.transform(b.U,c.U,a);else b&&c&&T.Ga[b.L()]&&T.Ga[b.L()][c.L()]&&T.Ga[b.L()][c.L()](a);return a};
var W=s({ja:["loadstart","loadend","reload","unload"],a:i,id:i,c:i,url:i,u:i,size:i,position:i,Ba:k,s:function(a,b,c,e,f,g){this.c=a;this.position=b.j();this.u=c.j();this.url=e;this.size=f.j();this.id=A("Tile_");this.a=new Ba(this,i,this.ja);u(this,g)},Qe:function(){if(this.Ba){this.Ba=k;this.a.o("unload")}},t:function(){this.position=this.size=this.u=this.c=i;this.a.t();this.a=i},j:function(a){if(a==i)a=new W(this.c,this.position,this.u,this.url,this.size);E(a,this);return a},P:function(){var a=
this.c.C;this.pd=a&&this.u.Vc(a,k)||this.c.Ec;this.clear();return this.pd},moveTo:function(a,b,c){if(c==i)c=d;this.u=a.j();this.position=b.j();c&&this.P()},clear:l(),Vd:function(a){var b=q("reprojectDeprecated",{layerName:this.c.name});p.warn(b);b=this.c.map.Mc(a);a=a.j();a.x+=this.size.h;a.y+=this.size.g;a=this.c.map.Mc(a);if(b.d>a.d)if(b.d<0)b.d=-180-(b.d+180);else a.d=180+a.d+180;return new O(b.d,a.f,a.d,b.f)},qd:function(){this.pd&&this.show()},show:l(),ra:l(),r:"OpenLayers.Tile"});
U.wd=s(U.gb,{J:50,F:i,s:function(a){this.F={};U.gb.prototype.s.apply(this,[a]);this.Lb([new U.Pan(U.Pan.nc,{J:this.J,F:this.F}),new U.Pan(U.Pan.oc,{J:this.J,F:this.F}),new U.Pan(U.Pan.mc,{J:this.J,F:this.F}),new U.Pan(U.Pan.rc,{J:this.J,F:this.F})])},r:"OpenLayers.Control.PanPanel"});U.Fd=s(U.gb,{s:function(a){U.gb.prototype.s.apply(this,[a]);this.Lb([new U.Dd,new U.Gd,new U.Ed])},r:"OpenLayers.Control.ZoomPanel"});
var Y=s({hb:{$e:100,pf:325,bf:725,sf:750,af:1E3},ja:["preaddlayer","addlayer","removelayer","changelayer","movestart","move","moveend","zoomend","popupopen","popupclose","addmarker","removemarker","clearmarkers","mouseover","mouseout","mousemove","dragstart","drag","dragend","changebaselayer"],id:i,Ub:k,a:i,ma:k,b:i,xa:k,size:i,v:i,$b:i,B:i,i:i,controls:i,ha:i,e:i,V:i,Za:i,zoom:0,ue:1.5,va:0,q:i,G:"EPSG:4326",z:"degrees",l:i,ea:1.40625,fa:i,Ca:i,Da:i,C:i,sa:i,H:i,xb:16,bb:i,nb:i,Ra:d,ga:i,A:i,ed:Ca,
te:50,cd:i,s:function(a,b){if(arguments.length===1&&typeof a==="object")a=(b=a)&&b.b;this.q=new N(Y.zd,Y.xd);this.C=new O(-180,-90,180,90);this.cd=new O(15,15,15,15);this.bb=aa()+"theme/default/style.css";u(this,b);this.i=[];this.id=A("OpenLayers.Map_");this.b=v(a);if(!this.b){this.b=document.createElement("div");this.b.style.height="1px";this.b.style.width="1px"}C.Na(this.b,"olMap");var c=this.id+"_OpenLayers_ViewPort";this.v=z(c,i,i,i,"relative",i,"hidden");this.v.style.width="100%";this.v.style.height=
"100%";this.v.className="olMapViewport";this.b.appendChild(this.v);c=this.id+"_OpenLayers_Container";this.B=z(c);this.B.style.zIndex=this.hb.Popup-1;this.v.appendChild(this.B);this.a=new Ba(this,this.b,this.ja,this.Ra,{Zb:d});this.Ha();this.A instanceof Object&&this.a.yb(this.A);this.a.Z("movestart",this,this.Ha);if(navigator.appName.indexOf("Microsoft")!=-1)this.a.Z("resize",this,this.Ha);else{this.Ib=r(this.Ha,this);B.D(window,"resize",this.Ib)}if(this.bb){c=d;for(var e=document.getElementsByTagName("link"),
f=0,g=e.length;f<g;++f)if(va(e.item(f).href,this.bb)){c=k;break}if(c){c=document.createElement("link");c.setAttribute("rel","stylesheet");c.setAttribute("type","text/css");c.setAttribute("href",this.bb);document.getElementsByTagName("head")[0].appendChild(c)}}if(this.controls==i)this.controls=U!=i?[new U.of,new U.qf,new U.Ye,new U.Ze]:[];f=0;for(g=this.controls.length;f<g;f++)this.tc(this.controls[f]);this.ha=[];this.eb=r(this.t,this);B.D(window,"unload",this.eb);if(b&&b.i){this.Id(b.i);b.V&&this.ia(b.V,
b.zoom)}},xg:function(a){this.b=v(a);C.Na(this.b,"olMap");this.a.yc(this.b);this.v.parentNode.removeChild(this.v);this.b.appendChild(this.v);this.Ha()},eb:i,Ib:i,t:function(){if(!this.eb)return k;if(this.ga){this.ga.stop();this.ga=i}B.Gb(window,"unload",this.eb);this.eb=i;this.Ib?B.Gb(window,"resize",this.Ib):this.a.kc("resize",this,this.Ha);this.cd=i;if(this.controls!=i){for(var a=this.controls.length-1;a>=0;--a)this.controls[a].t();this.controls=i}if(this.i!=i){for(a=this.i.length-1;a>=0;--a)this.i[a].t(k);
this.i=i}this.v&&this.b.removeChild(this.v);this.v=i;if(this.A){this.a.db(this.A);this.A=i}this.a.t();this.a=i},Cg:function(a){u(this,a)},cg:n("q"),Ic:function(a,b,c){var e=typeof c.test=="function";return ha(this[a],function(f){return f[b]==c||e&&c.test(f[b])})},Lc:function(a,b){return this.Ic("layers",a,b)},Yf:function(a){return this.Lc("name",a)},Xf:function(a){return this.Lc("CLASS_NAME",a)},qb:function(a,b){return this.Ic("controls",a,b)},Xd:function(a){return this.qb("CLASS_NAME",a)},Wf:function(a){for(var b=
i,c=0,e=this.i.length;c<e;c++){var f=this.i[c];if(f.id==a){b=f;break}}return b},hc:function(a,b){a.Fe(this.hb[a.R?"BaseLayer":"Overlay"]+b*5)},Be:function(){for(var a=0,b=this.i.length;a<b;a++)this.hc(this.i[a],a)},vc:function(a){for(var b=0,c=this.i.length;b<c;b++)if(this.i[b]==a){a=q("layerAlreadyAdded",{layerName:a.name});p.warn(a);return k}if(this.ma)a.R=k;if(this.a.o("preaddlayer",{c:a})!==k){a.b.className="olLayerDiv";a.b.style.overflow="";this.hc(a,this.i.length);a.ke?this.v.appendChild(a.b):
this.B.appendChild(a.b);this.i.push(a);a.Eb(this);if(a.R||this.ma&&!this.e)this.e==i?this.Db(a):a.ic(k);else a.I();this.a.o("addlayer",{c:a})}},Id:function(a){for(var b=0,c=a.length;b<c;b++)this.vc(a[b])},ye:function(a,b){if(b==i)b=d;a.ke?this.v.removeChild(a.b):this.B.removeChild(a.b);ja(this.i,a);a.map=i;if(this.e==a){this.e=i;if(b)for(var c=0,e=this.i.length;c<e;c++){var f=this.i[c];if(f.R||this.ma){this.Db(f);break}}}this.Be();this.a.o("removelayer",{c:a})},$f:function(){return this.i.length},
Jc:function(a){return w(this.i,a)},Ee:function(a,b){var c=this.Jc(a);if(b<0)b=0;else if(b>this.i.length)b=this.i.length;if(c!=b){this.i.splice(c,1);this.i.splice(b,0,a);c=0;for(var e=this.i.length;c<e;c++)this.hc(this.i[c],c);this.a.o("changelayer",{c:a,Ya:"order"});if(this.ma)if(b===0)this.Db(a);else this.e!==this.i[0]&&this.Db(this.i[0])}},ug:function(a,b){this.Ee(a,this.Jc(a)+b)},Db:function(a){if(a!=this.e)if(w(this.i,a)!=-1){var b=this.X(),c=I(this.de(),a.z);this.e!=i&&!this.ma&&this.e.ic(k);
this.e=a;this.va++;if(!this.ma||this.e.visibility)this.e.ic(d);if(b!=i)this.ia(b,this.tb(c||this.Za,d),k,d);this.a.o("changebaselayer",{c:this.e})}},Kb:function(a,b){this.controls.push(a);this.tc(a,b)},Lb:function(a,b){for(var c=arguments.length===1?[]:b,e=0,f=a.length;e<f;e++)this.Kb(a[e],c[e]?c[e]:i)},tc:function(a,b){a.se=a.b!=i;if(this.nb&&!a.nb)a.nb=this.nb;a.Eb(this);var c=a.P(b);if(c)if(!a.se){c.style.zIndex=this.hb.Control+this.controls.length;this.v.appendChild(c)}a.Pa&&a.la()},Wd:function(a){for(var b=
i,c=0,e=this.controls.length;c<e;c++){var f=this.controls[c];if(f.id==a){b=f;break}}return b},we:function(a){if(a&&a==this.Wd(a.id)){a.b&&a.b.parentNode==this.v&&this.v.removeChild(a.b);ja(this.controls,a)}},vf:function(a,b){if(b)for(var c=this.ha.length-1;c>=0;--c)this.ze(this.ha[c]);a.map=this;this.ha.push(a);if(c=a.P()){c.style.zIndex=this.hb.Popup+this.ha.length;this.B.appendChild(c)}},ze:function(a){ja(this.ha,a);if(a.b)try{this.B.removeChild(a.b)}catch(b){}a.map=i},Q:function(){var a=i;if(this.size!=
i)a=this.size.j();return a},Ha:function(){var a=this.Yd();if(a&&!isNaN(a.g)&&!isNaN(a.h)){this.a.Pb();var b=this.Q();if(b==i)this.size=b=a;if(!a.ba(b)){this.size=a;a=0;for(b=this.i.length;a<b;a++)this.i[a].bd();a=this.X();if(this.e!=i&&a!=i){b=this.zoom;this.zoom=i;this.ia(a,b)}}}},Yd:function(){var a=new N(this.b.clientWidth,this.b.clientHeight);if(a.h==0&&a.g==0||isNaN(a.h)&&isNaN(a.g)){a.h=this.b.offsetWidth;a.g=this.b.offsetHeight}if(a.h==0&&a.g==0||isNaN(a.h)&&isNaN(a.g)){a.h=parseInt(this.b.style.width);
a.g=parseInt(this.b.style.height)}return a},zc:function(a,b){var c=i;if(a==i)a=this.X();if(b==i)b=this.w();if(a!=i&&b!=i){var e=this.Q();c=e.h*b;e=e.g*b;c=new O(a.d-c/2,a.f-e/2,a.d+c/2,a.f+e/2)}return c},X:function(){var a=i;if(this.V)a=this.V.j();return a},gg:n("zoom"),Ab:function(a,b,c){c=E(c,{xc:d,xa:k});var e=this.za(this.X());a=e.add(a,b);if(!c.xa||!a.ba(e)){e=this.ya(a);c.xc?this.ve(e):this.ia(e,i,c.xa)}},ve:function(a){if(this.ed&&this.ca().scale(this.ue).Cc(a)){if(!this.ga)this.ga=new Da(this.ed);
var b=this.X();a.d==b.d&&a.f==b.f||this.ga.start({d:b.d,f:b.f},{d:a.d,f:a.f},this.te,{K:{start:r(function(){this.a.o("movestart")},this),Gc:r(function(c){c=new R(c.d,c.f);this.moveTo(c,this.zoom,{dragging:d,noEvent:d})},this),Fc:r(function(c){c=new R(c.d,c.f);this.moveTo(c,this.zoom,{noEvent:d});this.a.o("moveend")},this)}})}else this.ia(a)},ia:function(a,b,c,e){this.moveTo(a,b,{dragging:c,forceZoomChange:e,caller:"setCenter"})},moveTo:function(a,b,c){c||(c={});if(b!=i){b=parseFloat(b);this.Ub||(b=
Math.round(b))}var e=c.xa,f=c.Mf,g=c.pg;this.ga&&c.caller=="setCenter"&&this.ga.stop();if(!this.V&&!this.Xc(a))a=this.C.pa();if(this.H!=i){if(a==i)a=this.X();if(b==i)b=this.zoom;c=this.zc(a,this.Ta(b));if(!this.H.Rb(c)){var h=this.H.pa();if(c.M()>this.H.M())a=new R(h.d,a.f);else if(c.left<this.H.left)a=a.add(this.H.left-c.left,0);else if(c.right>this.H.right)a=a.add(this.H.right-c.right,0);if(c.da()>this.H.da())a=new R(a.d,h.f);else if(c.bottom<this.H.bottom)a=a.add(0,this.H.bottom-c.bottom);else if(c.top>
this.H.top)a=a.add(0,this.H.top-c.top)}}f=f||this.Yc(b)&&b!=this.zoom;c=this.Xc(a)&&!a.ba(this.V);if(f||c||!e){!this.xa&&!g&&this.a.o("movestart");if(c){!f&&this.V&&this.Qd(a);this.V=a.j()}if(f||this.$b==i){this.$b=this.V.j();this.B.style.left="0px";this.B.style.top="0px"}if(f){this.zoom=b;this.Za=this.Ta(b);this.va++}a=this.ca();if(this.e.visibility){this.e.moveTo(a,f,e);e?this.e.a.o("move"):this.e.a.o("moveend",{zoomChanged:f})}a=this.e.ca();b=0;for(c=this.i.length;b<c;b++){h=this.i[b];if(h!==this.e&&
!h.R){var j=h.mb();if(h.inRange!=j){(h.inRange=j)||h.display(k);this.a.o("changelayer",{c:h,Ya:"visibility"})}if(j&&h.visibility){h.moveTo(a,f,e);e?h.a.o("move"):h.a.o("moveend",{zoomChanged:f})}}}if(f){b=0;for(c=this.ha.length;b<c;b++)this.ha[b].Og()}this.a.o("move");f&&this.a.o("zoomend")}!e&&!g&&this.a.o("moveend");this.xa=!!e},Qd:function(a){var b=this.za(this.$b);a=this.za(a);if(b!=i&&a!=i){this.B.style.left=Math.round(b.x-a.x)+"px";this.B.style.top=Math.round(b.y-a.y)+"px"}},Yc:function(a){return a!=
i&&a>=0&&a<this.be()},Xc:function(a){var b=k;if(a!=i)b=this.Sa().Cc(a);return b},ag:function(){var a=this.Nc();return a?a.L():i},Nc:function(){var a=i;if(this.e!=i)a=this.e.G;return a},Zf:function(){var a=i;if(this.e!=i)a=this.e.ea;return a},Sa:function(a){var b=i;if(a&&a.Ce&&this.H)b=this.H;else if(this.e!=i)b=this.e.C;return b},be:function(){var a=i;if(this.e!=i)a=this.e.xb;return a},ca:function(){var a=i;if(this.e!=i)a=this.e.ca();return a},w:function(){var a=i;if(this.e!=i)a=this.e.w();else if(this.ma===
d&&this.i.length>0)a=this.i[0].w();return a},sb:function(){var a=i;if(this.e!=i)a=this.e.z;return a},de:function(){var a=i;if(this.e!=i)a=L(this.w(),this.e.z);return a},Yb:function(a,b){var c=i;if(this.e!=i)c=this.e.Yb(a,b);return c},Ta:function(a){var b=i;if(this.e)b=this.e.Ta(a);return b},tb:function(a,b){var c=i;if(this.e!=i)c=this.e.tb(a,b);return c},sd:function(a){this.Yc(a)&&this.ia(i,a)},Ve:function(){this.sd(this.zoom+1)},We:function(){this.sd(this.zoom-1)},td:function(a,b){var c=a.pa();if(this.e.$){c=
this.Sa();for(a=a.j();a.right<a.left;)a.right+=c.M();c=a.pa().$(c)}this.ia(c,this.Yb(a,b))},Xe:function(a){this.td(this.Sa({restricted:a?a.Ce:d}))},Sg:function(a,b){var c=I(a,this.e.z),e=this.Q(),f=e.h*c;c=e.g*c;e=this.X();this.td(new O(e.d-f/2,e.f-c/2,e.d+f/2,e.f+c/2),b)},ya:function(a){var b=i;if(this.e!=i)b=this.e.ya(a);return b},za:function(a){var b=i;if(this.e!=i)b=this.e.za(a);return b},$d:function(a){return this.ya(a)},ce:function(a){a=this.za(a);a.x=Math.round(a.x);a.y=Math.round(a.y);return a},
Uf:function(a){var b=a?this.$d(a):this.X()||new R(0,0),c=this.w();a=b.add(-c/2,0);var e=b.add(c/2,0),f=b.add(0,-c/2);b=b.add(0,c/2);c=new T("EPSG:4326");var g=this.Nc()||c;if(!g.ba(c)){a.transform(g,c);e.transform(g,c);f.transform(g,c);b.transform(g,c)}return new N(sa(a,e),sa(f,b))},Qc:function(a){var b=i;if(a!=i)b=a.add(parseInt(this.B.style.left),parseInt(this.B.style.top));return b},Zd:function(a){var b=i;if(a!=i){b=a.add(-parseInt(this.B.style.left),-parseInt(this.B.style.top));if(isNaN(b.x)||
isNaN(b.y))b=i}return b},Mc:function(a){a=this.Qc(a);return this.ya(a)},Kc:function(a){return this.Zd(this.ce(a))},r:"OpenLayers.Map"});Y.zd=256;Y.xd=256;
W.Ka=s(W,{url:i,p:i,frame:i,Wa:i,Wc:k,Zc:1,vb:d,n:i,me:i,s:function(a,b,c,e){W.prototype.s.apply(this,arguments);this.me!=i&&u(this,W.Ka.cf);this.url=e;this.frame=document.createElement("div");this.frame.style.overflow="hidden";this.frame.style.position="absolute";this.Wa=this.c.Ld&&oa()},t:function(){this.p!=i&&this.xe();this.p=i;this.frame!=i&&this.frame.parentNode==this.c.b&&this.c.b.removeChild(this.frame);this.frame=i;if(this.n){this.n.t();this.n=i}this.c.a.kc("loadend",this,this.fc);W.prototype.t.apply(this,
arguments)},j:function(a){if(a==i)a=new W.Ka(this.c,this.position,this.u,this.url,this.size);a=W.prototype.j.apply(this,[a]);a.p=i;return a},P:function(){if(this.c!=this.c.map.e&&this.c.Ae)this.u=this.Vd(this.position);var a=W.prototype.P.apply(this,arguments);if(w(this.c.pc,this.c.jc)!=-1||this.c.$a)if(a){if(!this.n){this.n=this.j();this.n.ra();this.n.Wc=d;this.a.Z("loadend",this,this.fc);this.c.a.Z("loadend",this,this.fc)}this.He()}else this.n&&this.n.clear();else if(a&&this.vb){this.a.Z("loadend",
this,this.qd);this.vb=k}if(!a)return k;if(this.Ba)this.a.o("reload");else{this.Ba=d;this.a.o("loadstart")}return this.jd()},fc:function(){this.qd();if(this.n&&(this.vb||!this.c.Xa)){this.vb=k;var a=this.c.C;if(a&&this.u.Vc(a,k)){this.n.position=this.position;this.n.u=this.u;this.n.size=this.size;this.n.ub=this.c.Wb(this.u)||this.size;this.n.Va=this.c.Va;this.n.Za=this.c.w();this.n.jd()}this.n.ra()}},jd:function(){if(this.c.async){this.Tc();this.c.dg(this.u,this,"url",this.fd)}else{this.url=this.c.Pc(this.u);
this.Tc();this.fd()}return d},fd:function(){if(this.c!==i){y(this.frame,i,this.position,this.size);var a=this.c.Wb(this.u);if(this.Wa)pa(this.p,i,i,a,this.url);else{y(this.p,i,i,a);this.p.src=this.url}}},clear:function(){if(this.p){this.ra();if(W.Ka.Se)this.p.src=aa()+"img/blank.gif"}},Tc:function(){if(this.p==i){var a=this.c.Va,b=this.c.Wb(this.u);this.p=this.Wa?qa(i,a,b,i,"relative",i,i,i,d):ka(i,a,b,i,"relative",i,i,d);if(this.c.url instanceof Array)this.p.rd=this.c.url.slice();this.p.className=
"olTileImage";this.frame.style.zIndex=this.Wc?0:1;this.frame.appendChild(this.p);this.c.b.appendChild(this.frame);this.c.opacity!=i&&y(this.p,i,i,i,i,i,i,this.c.opacity);this.p.map=this.c.map;var c=function(){if(this.Ba){this.Ba=k;this.a.o("loadend")}};this.Wa?B.D(this.p.childNodes[0],"load",r(c,this)):B.D(this.p,"load",r(c,this));B.D(this.p,"error",r(function(){this.p.ib>0&&c.call(this)},this))}this.p.va=this.c.map.va},xe:function(){B.ab(this.p);if(this.p.parentNode==this.frame){this.frame.removeChild(this.p);
this.p.map=i}this.p.rd=i;var a=this.p.firstChild;if(a){B.ab(a);this.p.removeChild(a);delete a}else this.p.src=aa()+"img/blank.gif"},Bf:function(){if(this.c)va(this.Wa?this.p.firstChild.src:this.p.src,this.url)||this.ra()},He:function(){if(this.n&&this.n.p){var a=1;if(this.n.Za)a=this.n.Za/this.c.w();if(a!=this.Zc){if(this.c.jc=="resize"){var b=new R(this.n.u.left,this.n.u.top),c=new N(this.n.size.h*a,this.n.size.g*a);b=this.c.map.Kc(b);y(this.n.frame,i,b,c);c=this.n.ub;c=new N(c.h*a,c.g*a);if(b=this.n.Va)b=
new P(b.x*a,b.y*a);y(this.n.p,i,b,c);this.n.show()}}else this.c.$a?this.n.show():this.n.ra();this.Zc=a}},show:function(){this.frame.style.display="";if(w(this.c.pc,this.c.jc)!=-1)if(navigator.userAgent.toLowerCase().indexOf("gecko")!=-1)this.frame.scrollLeft=this.frame.scrollLeft},ra:function(){this.frame.style.display="none"},r:"OpenLayers.Tile.Image"});W.Ka.Se=xa()=="safari"||xa()=="opera";
var $=s({id:i,name:i,b:i,opacity:i,Ob:i,ja:["loadstart","loadend","loadcancel","visibilitychanged","move","moveend"],La:["scales","resolutions","maxScale","minScale","maxResolution","minResolution","numZoomLevels","maxZoomLevel"],a:i,map:i,R:k,Ld:k,If:d,visibility:d,Af:i,inRange:k,ub:i,Va:i,options:i,A:i,qa:0,G:i,z:i,Cb:i,l:i,C:i,sa:i,ea:i,fa:i,xb:i,Da:i,Ca:i,Ec:k,$:k,jc:i,pc:["resize"],og:{},s:function(a,b){this.Jd(b);this.name=a;if(this.id==i){this.id=A(this.r+"_");this.b=z(this.id);this.b.style.width=
"100%";this.b.style.height="100%";this.b.dir="ltr";this.a=new Ba(this,this.b,this.ja);this.A instanceof Object&&this.a.yb(this.A)}if(this.$)this.Ec=d},t:function(a){if(a==i)a=d;this.map!=i&&this.map.ye(this,a);this.options=this.b=this.name=this.map=this.G=i;if(this.a){this.A&&this.a.db(this.A);this.a.t()}this.a=this.A=i},j:function(a){if(a==i)a=new $(this.name,this.rb());E(a,this);a.map=i;return a},rb:function(){var a={},b;for(b in this.options)a[b]=this[b];return a},Ag:function(a){if(a!=this.name){this.name=
a;this.map!=i&&this.map.a.o("changelayer",{c:this,Ya:"name"})}},Jd:function(a){if(this.options==i)this.options={};u(this.options,a);u(this,a);if(typeof this.G=="string")this.G=new T(this.G);if(this.G&&this.G.sb())this.z=this.G.sb();if(this.map){var b=this.La.concat(["projection","units","minExtent","maxExtent"]),c;for(c in a)if(a.hasOwnProperty(c)&&w(b,c)>=0){this.Uc();break}}},bd:l(),I:function(){var a=k;if(this.map){this.inRange=this.mb();var b=this.ca();if(b&&this.inRange&&this.visibility){this.moveTo(b,
d,k);this.a.o("moveend",{zoomChanged:d});a=d}}return a},moveTo:function(){var a=this.visibility;this.R||(a=a&&this.inRange);this.display(a)},Eb:function(a){if(this.map==i){this.map=a;this.C=this.C||this.map.C;this.sa=this.sa||this.map.sa;this.G=this.G||this.map.G;if(typeof this.G=="string")this.G=new T(this.G);this.z=this.G.sb()||this.z||this.map.z;this.Uc();if(!this.R){this.inRange=this.mb();this.b.style.display=this.visibility&&this.inRange?"":"none"}this.Fb()}},yf:l(),wg:l(),Wb:function(){return this.ub||
this.q},Fb:function(a){this.q=a=a?a:this.q?this.q:this.map.q;if(this.qa){this.Va=new P(-this.qa,-this.qa);this.ub=new N(a.h+2*this.qa,a.g+2*this.qa)}},eg:n("visibility"),ic:function(a){if(a!=this.visibility){this.visibility=a;this.display(a);this.I();this.map!=i&&this.map.a.o("changelayer",{c:this,Ya:"visibility"});this.a.o("visibilitychanged")}},display:function(a){if(a!=(this.b.style.display!="none"))this.b.style.display=a&&this.mb()?"block":"none"},mb:function(){var a=k;if(this.Ob)a=d;else if(this.map){a=
this.map.w();a=a>=this.fa&&a<=this.ea}return a},zg:function(a){if(a!=this.R){this.R=a;this.map!=i&&this.map.a.o("changebaselayer",{c:this})}},Uc:function(){var a,b,c={},e=d;a=0;for(b=this.La.length;a<b;a++){var f=this.La[a];c[f]=this.options[f];if(e&&this.options[f])e=k}if(this.Ob==i)this.Ob=e;if(c.l==i)c.l=this.kd(c.Cb);if(c.l==i)c.l=this.Ac(c);if(c.l==i){a=0;for(b=this.La.length;a<b;a++){f=this.La[a];c[f]=this.options[f]!=i?this.options[f]:this.map[f]}if(c.l==i)c.l=this.kd(c.Cb);if(c.l==i)c.l=this.Ac(c)}var g;
if(this.options.ea&&this.options.ea!=="auto")g=this.options.ea;if(this.options.Da)g=I(this.options.Da,this.z);var h;if(this.options.fa&&this.options.fa!=="auto")h=this.options.fa;if(this.options.Ca)h=I(this.options.Ca,this.z);if(c.l){c.l.sort(function(j,m){return m-j});g||(g=c.l[0]);h||(h=c.l[c.l.length-1])}if(this.l=c.l){b=this.l.length;this.Cb=Array(b);for(a=0;a<b;a++)this.Cb[a]=L(this.l[a],this.z);this.xb=b}if(this.fa=h)this.Ca=L(h,this.z);if(this.ea=g)this.Da=L(g,this.z)},kd:function(a){if(a!=
i){var b,c,e;e=a.length;b=Array(e);for(c=0;c<e;c++)b[c]=I(a[c],this.z);return b}},Ac:function(a){var b=a.ea;if(a.Da!=i)b=I(a.Da,this.z);else if(b=="auto"&&this.C!=i){var c=this.map.Q(),e=this.C.M()/c.h;c=this.C.da()/c.g;b=Math.max(e,c)}e=a.fa;if(a.Ca!=i)e=I(a.Ca,this.z);else if(a.fa=="auto"&&this.sa!=i){c=this.map.Q();e=this.sa.M()/c.h;c=this.sa.da()/c.g;e=Math.max(e,c)}c=a.ng;a=a.xb;if(typeof e==="number"&&typeof b==="number"&&a===undefined)a=Math.floor(Math.log(b/e)/Math.log(2))+1;else if(a===undefined&&
c!=i)a=c+1;if(!(typeof a!=="number"||a<=0||typeof b!=="number"&&typeof e!=="number")){c=Array(a);var f=2;if(typeof e=="number"&&typeof b=="number")f=Math.pow(b/e,1/(a-1));var g;if(typeof b==="number")for(g=0;g<a;g++)c[g]=b/Math.pow(f,g);else for(g=0;g<a;g++)c[a-1-g]=e*Math.pow(f,g);return c}},w:function(){return this.Ta(this.map.zoom)},ca:function(){return this.map.zc()},Yb:function(a,b){var c=this.map.Q();return this.tb(Math.max(a.M()/c.h,a.da()/c.g),b)},Rf:l(),Ta:function(a){a=Math.max(0,Math.min(a,
this.l.length-1));if(this.map.Ub){var b=Math.floor(a);a=this.l[b]-(a-b)*(this.l[b]-this.l[Math.ceil(a)])}else a=this.l[Math.round(a)];return a},tb:function(a,b){var c;if(this.map.Ub){var e=0,f=this.l[e],g=this.l[this.l.length-1],h;c=0;for(var j=this.l.length;c<j;++c){h=this.l[c];if(h>=a){f=h;e=c}if(h<=a){g=h;break}}c=f-g;c=c>0?e+(f-a)/c:e}else{f=Number.POSITIVE_INFINITY;c=0;for(j=this.l.length;c<j;c++)if(b){e=Math.abs(this.l[c]-a);if(e>f)break;f=e}else if(this.l[c]<a)break;c=Math.max(0,c-1)}return c},
ya:function(a){var b=i;if(a!=i){var c=this.map.Q(),e=this.map.X();if(e){b=this.map.w();b=new R(e.d+(a.x-c.h/2)*b,e.f-(a.y-c.g/2)*b);if(this.$)b=b.$(this.C)}}return b},za:function(a){var b=i;if(a!=i){b=this.map.w();var c=this.map.ca();b=new P(1/b*(a.d-c.left),1/b*(c.top-a.f))}return b},Bg:function(a){if(a!=this.opacity){this.opacity=a;for(var b=0,c=this.b.childNodes.length;b<c;++b)y(this.b.childNodes[b].firstChild,i,i,i,i,i,i,a);this.map!=i&&this.map.a.o("changelayer",{c:this,Ya:"opacity"})}},fg:function(){return this.b.style.zIndex},
Fe:function(a){this.b.style.zIndex=a},xf:function(a){if(this.qa){var b=this.qa*this.map.w();a=new O(a.left-b,a.bottom-b,a.right+b,a.top+b)}if(this.$)a=a.$(this.C,{rightTolerance:this.w()});return a},r:"OpenLayers.Layer"});
$.ka=s($,{Cd:(Math.sqrt(5)-1)/2,url:i,ua:i,Ae:k,s:function(a,b,c,e){var f=arguments;f=[a,e];$.prototype.s.apply(this,f);this.url=b;this.ua=u({},c)},t:function(){this.ua=this.url=i;$.prototype.t.apply(this,arguments)},j:function(a){if(a==i)a=new $.ka(this.name,this.url,this.ua,this.rb());return a=$.prototype.j.apply(this,[a])},Dg:function(a){this.url=a},ne:function(a){this.ua=u(this.ua,a);a=this.I();this.map!=i&&this.map.a.o("changelayer",{c:this,Ya:"params"});return a},I:function(a){return a?this.ne({_olSalt:Math.random()}):
$.prototype.I.apply(this,[])},md:function(a,b){for(var c=1,e=0,f=a.length;e<f;e++){c*=a.charCodeAt(e)*this.Cd;c-=Math.floor(c)}return b[Math.floor(c*b.length)]},Tf:function(a,b){var c=b||this.url,e=u({},this.ua);e=u(e,a);var f=ra(e);if(c instanceof Array)c=this.md(f,c);f=ta(c);var g={},h;for(h in f)g[h.toUpperCase()]=f[h];for(var j in e)j.toUpperCase()in g&&delete e[j];e=f=ra(e);h=c;if(e){c=(c+" ").split(/[?&]/);h+=c.pop()===" "?e:c.length?"&"+e:"?"+e}return h},r:"OpenLayers.Layer.HTTPRequest"});
$.fb=s($.ka,{q:i,Fg:i,k:i,$a:k,Bb:1.5,na:2,Xa:0,s:function(){$.ka.prototype.s.apply(this,arguments);this.a.Mb("tileloaded");this.k=[]},t:function(){this.Bc();this.q=this.k=i;$.ka.prototype.t.apply(this,arguments)},Bc:function(){if(this.k){for(var a=0,b=this.k.length;a<b;a++)for(var c=this.k[a],e=0,f=c.length;e<f;e++){var g=c[e];this.ec(g);g.t()}this.k=[]}},j:function(a){if(a==i)a=new $.fb(this.name,this.url,this.ua,this.rb());a=$.ka.prototype.j.apply(this,[a]);if(this.q!=i)a.q=this.q.j();a.k=[];return a},
moveTo:function(a,b,c){$.ka.prototype.moveTo.apply(this,arguments);a=a||this.map.ca();if(a!=i){var e=!this.k.length||b,f=this.Oc();if(this.$a){if(e||!c&&!f.Rb(a))this.je(a)}else e||!f.Rb(a,d)?this.ie(a):this.oe(a)}},Fb:function(a){if(this.$a){a=this.map.Q();a.g=parseInt(a.g*this.Bb);a.h=parseInt(a.h*this.Bb)}$.ka.prototype.Fb.apply(this,[a])},Vf:function(){p.warn("The getGridBounds() function is deprecated. It will be removed in 3.0. Please use getTilesBounds() instead.");return this.Oc()},Oc:function(){var a=
i;if(this.k.length){a=this.k[this.k.length-1][0];var b=this.k[0][this.k[0].length-1];a=new O(a.u.left,a.u.bottom,b.u.right,b.u.top)}return a},je:function(a){var b=a.pa(),c=a.M()*this.Bb;a=a.da()*this.Bb;b=new O(b.d-c/2,b.f-a/2,b.d+c/2,b.f+a/2);c=this.map.Kc(new R(b.left,b.top));this.k.length||(this.k[0]=[]);if(a=this.k[0][0])a.moveTo(b,c);else{a=this.Nb(b,c);this.wc(a);a.P();this.k[0][0]=a}this.hd(1,1)},Od:function(a,b,c){var e=c*this.q.h;c=c*this.q.g;var f=a.left-b.left,g=Math.floor(f/e)-this.na;
a=a.top-(b.bottom+c);var h=Math.ceil(a/c)+this.na;return{Ke:e,Je:c,Me:b.left+g*e,Le:b.bottom+h*c,Ne:-(f/e-g)*this.q.h,Oe:-(h-a/c)*this.q.g}},ie:function(a){var b=this.map.Q(),c=Math.ceil(b.g/this.q.g)+Math.max(1,2*this.na);b=Math.ceil(b.h/this.q.h)+Math.max(1,2*this.na);var e=this.Od(a,this.Sa(),this.map.w()),f=Math.round(e.Ne),g=Math.round(e.Oe),h=e.Me,j=e.Le,m=e.Ke;e=e.Je;this.origin=new P(f,g);var x=f,t=h,D=0,J=parseInt(this.map.B.style.left),Z=parseInt(this.map.B.style.top);do{var K=this.k[D++];
if(!K){K=[];this.k.push(K)}h=t;f=x;var M=0;do{var S=new O(h,j,h+m,j+e),X=f;X-=J;var Q=g;Q-=Z;X=new P(X,Q);if(Q=K[M++])Q.moveTo(S,X,k);else{Q=this.Nb(S,X);this.wc(Q);K.push(Q)}h+=m;f+=this.q.h}while(h<=a.right+m*this.na||M<b);j-=e;g+=this.q.g}while(j>=a.bottom-e*this.na||D<c);this.hd(D,M);this.Ge()},Sa:n("C"),Ge:function(){for(var a=[],b=["right","down","left","up"],c=0,e=-1,f=w(b,"right"),g=0;g<b.length;){var h=c,j=e;switch(b[f]){case "right":j++;break;case "down":h++;break;case "left":j--;break;
case "up":h--}var m=i;if(h<this.k.length&&h>=0&&j<this.k[0].length&&j>=0)m=this.k[h][j];if(m!=i&&!m.gd){a.unshift(m);m.gd=d;g=0;c=h;e=j}else{f=(f+1)%4;g++}}b=0;for(c=a.length;b<c;b++){m=a[b];m.P();m.gd=k}},Nb:l(),wc:function(a){a.ad=function(){this.Xa==0&&this.a.o("loadstart");this.Xa++};a.a.Z("loadstart",this,a.ad);a.zb=function(){this.Xa--;this.a.o("tileloaded");this.Xa==0&&this.a.o("loadend")};a.a.Z("loadend",this,a.zb);a.a.Z("unload",this,a.zb)},ec:function(a){a.Qe();a.a.db({loadstart:a.ad,loadend:a.zb,
unload:a.zb,scope:this})},oe:function(){for(var a=this.na||1;;){var b=this.map.Qc(this.k[0][0].position);if(b.x>-this.q.h*(a-1))this.nd(d);else if(b.x<-this.q.h*a)this.nd(k);else if(b.y>-this.q.g*(a-1))this.od(d);else if(b.y<-this.q.g*a)this.od(k);else break}},od:function(a){for(var b=this.k,c=b[a?0:this.k.length-1],e=a?-this.q.g:this.q.g,f=this.map.w()*-e,g=a?b.pop():b.shift(),h=0,j=c.length;h<j;h++){var m=c[h],x=m.u.j();m=m.position.j();x.bottom+=f;x.top+=f;m.y+=e;g[h].moveTo(x,m)}a?b.unshift(g):
b.push(g)},nd:function(a){for(var b=a?-this.q.h:this.q.h,c=this.map.w()*b,e=0,f=this.k.length;e<f;e++){var g=this.k[e],h=g[a?0:g.length-1],j=h.u.j();h=h.position.j();j.left+=c;j.right+=c;h.x+=b;var m=a?this.k[e].pop():this.k[e].shift();m.moveTo(j,h);a?g.unshift(m):g.push(m)}},hd:function(a,b){for(;this.k.length>a;)for(var c=this.k.pop(),e=0,f=c.length;e<f;e++){var g=c[e];this.ec(g);g.t()}for(;this.k[0].length>b;){e=0;for(f=this.k.length;e<f;e++){c=this.k[e];g=c.pop();this.ec(g);g.t()}}},bd:function(){if(this.$a){this.Bc();
this.Fb()}},bg:function(a){var b=this.C,c=this.w(),e=c*this.q.h;c=c*this.q.g;var f=this.ya(a);a=b.left+e*Math.floor((f.d-b.left)/e);b=b.bottom+c*Math.floor((f.f-b.bottom)/c);return new O(a,b,a+e,b+c)},r:"OpenLayers.Layer.Grid"});
$.qc=s($.fb,{R:d,Sd:"image/png",gc:i,s:function(a,b,c,e){this.$c=c;$.fb.prototype.s.apply(this,[a,b,{},e]);this.pb=this.Sd.split("/")[1].toLowerCase();this.pb=this.pb=="jpg"?"jpeg":this.pb},j:function(a){if(a==i)a=new $.qc(this.name,this.url,this.$c,this.rb());return a=$.fb.prototype.j.apply(this,[a])},Pc:function(a){function b(h,j){h=String(h);for(var m=[],x=0;x<j;++x)m.push("0");return m.join("").substring(0,j-h.length)+h}var c=this.map.w(),e=this.C,f=this.q,g=Math.round((a.left-e.left)/(c*f.h));
a=Math.round((a.bottom-e.bottom)/(c*f.g));c=[this.$c,b(this.gc!=i?w(this.gc,c):this.map.zoom,2),b(parseInt(g/1E6),3),b(parseInt(g/1E3)%1E3,3),b(parseInt(g)%1E3,3),b(parseInt(a/1E6),3),b(parseInt(a/1E3)%1E3,3),b(parseInt(a)%1E3,3)+"."+this.pb].join("/");g=this.url;if(g instanceof Array)g=this.md(c,g);g=g.charAt(g.length-1)=="/"?g:g+"/";return g+c},Nb:function(a,b){var c=this.Pc(a);return new W.Ka(this,b,a,c,this.q)},r:"OpenLayers.Layer.TileCache"});var Ea;
window.init=function(){Ea=new Y("map",{l:[0.087890625,0.0439453125,0.02197265625,0.010986328125],bb:i,controls:[new U.wd({F:{xc:k}}),new U.Fd]});var a=new $.qc("TileCache Layer",["http://c0.tilecache.osgeo.org/wms-c/cache/","http://c1.tilecache.osgeo.org/wms-c/cache/","http://c2.tilecache.osgeo.org/wms-c/cache/","http://c3.tilecache.osgeo.org/wms-c/cache/","http://c4.tilecache.osgeo.org/wms-c/cache/"],"basic",{gc:[0.703125,0.3515625,0.17578125,0.087890625,0.0439453125,0.02197265625,0.010986328125,
0.0054931640625,0.00274658203125,0.001373291015625,6.866455078125E-4,3.4332275390625E-4,1.71661376953125E-4,8.58306884765625E-5,4.291534423828125E-5,2.1457672119140625E-5]});Ea.vc(a);Ea.ia(new R(5,40),5)};